### ISSUE TITLE
Question about the exp setting

### ISSUE THREAD

**Issue by miboyu24** [ripl/Transcrib3D#1]
Hello,

 Thanks for this impressive work! I wonder the evaluation setting on Nr3D/Sr3D. Did you use the mask3D segmentation bbox or gt bbox? Btw, would you mind sharing the mask3D segmentation result? 

Thanks,
boyu

**Comment by jiadingfang** [comment]
Hi Boyu,

Thanks for the interest in our paper. In Nr3D and Sr3D, we use dataset-provided bbox and annotations, while in ScanRefer we use predicted bbox using Mask3D. As stated in the "Referit3D" paper, 

> " To overcome this and decouple the 3D instance-segmentation problem from our referential setting, we assume access to the instance-level object segmentations of the underlying scene". 

Essentially, in Referit3D, we are dealing with a _classification_ problem, while in ScanRefer, we are dealing with a _regression_ problem.

Hope it helps. Please let us know if you have any other questions.

**Comment by miboyu24** [comment]
Thank you for reply. 
I have another question about the way you get the class label for each gt bbox in Nr3D/Sr3D setting. Did you use the gt class labels or mask3D predicted labels?

**Comment by jiadingfang** [comment]
Sorry for the late reply and thanks for the question. The original paper uses gt class labels. But we are also training a pointcloud classifier on ScanNet which takes in segemented pointcloud and predicts class labels. Given the high accuracy of SOTA pointcloud classification models (>90%), we expect the final overall performance to be similar. We will update the results in next version of the paper.

**Comment by miboyu24** [comment]
Thanks!
